[package]
name = "findr"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version="4.5.40", features=["derive"]}
crossterm = "0.29.0"
dirs = "6.0.0"
edit = "0.1.5"
ignore = "0.4.23"
lazy_static = "1.5.0"
nucleo = "0.5.0"
ratatui = "0.29.0"
syntect = "5.2.0"
