[package]
name = "findr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
crossterm = "0.29.0"
dirs = "6.0.0"
lazy_static = "1.5.0"
nucleo = "0.5.0"
ratatui = "0.29.0"
syntect = "5.2.0"
